DROP TABLE IF EXISTS BRANDS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS PRICE_LIST;
DROP TABLE IF EXISTS PRICES;

CREATE TABLE BRANDS (
	id INT PRIMARY KEY,
	name VARCHAR(64) NOT NULL
);

CREATE TABLE PRODUCTS (
	id INT PRIMARY KEY,
	name VARCHAR(64) NOT NULL
);

CREATE TABLE PRICE_LIST (
	id INT PRIMARY KEY
);

CREATE TABLE PRICES (
	brandId INT,
	productId INT,
	startDate TIMESTAMP,
	endDate TIMESTAMP,
	priority INT,
	price DECIMAL(6, 2) NOT NULL,
	priceList INT NOT NULL,
	CURRENCY VARCHAR(3) NOT NULL,
	lastUpdate TIMESTAMP,
	lastUpdateBy VARCHAR(32),
	FOREIGN KEY (brandId) REFERENCES BRANDS(id),
	FOREIGN KEY (productId) REFERENCES PRODUCTS(id),
	FOREIGN KEY (priceList) REFERENCES PRICE_LIST(id),
	PRIMARY KEY (brandId, productId, startDate, endDate, priority)
);